Added TDIGEST.MERGESTORE command and made TDIGEST.CREATE compression optional
RedisBloom/RedisBloom pull request #487
Opened 2022-07-26 13:27 UTC by filipecosta90

This PR adds a new command for the T-Digest datastructure, which allows to merge multiple t-digests into a new key. 
It has a similar look and feel like https://redis.io/commands/zinterstore/ . 
If destination already exists, it is overwritten. 

```
TDIGEST.MERGESTORE {destination} numkeys from-key [from-key ...] [COMPRESSION compression]
```

Apart from it, after discussing with @gkorland about the default compression, we've made COMPRESSION on `TDIGEST.CREATE` optional.

2022-07-27 09:46 UTC, ashtul reviewed
Nice addition.
Small comments

2022-07-27 09:46 UTC, ashtul commented on src/rm_tdigest.c
> +    if (argc == 3 && RedisModule_StringToLongLong(argv[2], &compression) != REDISMODULE_OK) {
`if(compression <= 0)`? or reuse `_TDigest_ParseCompressionParameter`

2022-07-27 09:46 UTC, ashtul commented on src/rm_tdigest.c
> +    if (RedisModule_StringToLongLong(argv[2], &numkeys) != REDISMODULE_OK) {
check for negative value

2022-07-27 13:15 UTC, ashtul submitted a review, later dismissed

2022-07-27 13:40 UTC, ashtul submitted a review, later dismissed

2022-07-27 14:21 UTC, ashtul approved these changes

2022-07-27 15:09 UTC, LiorKogan requested changes

2022-07-28 03:52 UTC, LiorKogan approved these changes

2022-07-28 10:03 UTC, merged