Update cuckoo-filter.md
RedisBloom/RedisBloom pull request #679
Opened 2023-10-03 17:13 UTC by sav-norem

update cuckoo md to include tabbed example shortcodes

2023-10-03 17:43 UTC, sav-norem commented
@dwdougherty if you could check this out and let me know if it needs any fixes!

2023-10-04 14:04 UTC, dwdougherty requested changes
Style changes and a question about the capacity used.

I did a test build and it looks fine in situ.

2023-10-24 14:38 UTC, sav-norem commented on docs/docs/cuckoo-filter.md
> +> We'll ddemonstrate creating an empty cuckoo filter with an initial capacity (of 1000 items), adding items to it, checking if they exist, and deleting them. While the `CF.ADD` command will create a
qq: is that quotation on the end missing an open quote or am I missing something else? also yes - that capacity is 1,000,000 so I'll correct that

2023-10-24 20:23 UTC, dwdougherty commented on docs/docs/cuckoo-filter.md
> +> We'll ddemonstrate creating an empty cuckoo filter with an initial capacity (of 1000 items), adding items to it, checking if they exist, and deleting them. While the `CF.ADD` command will create a
Definitely a stray quotation mark. Sorry 'bout that.

2023-10-30 15:43 UTC, dwdougherty approved these changes
LGTM

2023-11-15 10:15 UTC, sav-norem commented
merged into PR #670

2023-11-15 10:15 UTC, closed without merging