Update count-min-sketch.md
RedisBloom/RedisBloom pull request #680
Opened 2023-10-05 14:54 UTC by sav-norem

update count min sketch with hugo shortcodes and slightly more robust example of the CMS data type

2023-10-06 16:25 UTC, dwdougherty commented on docs/docs/count-min-sketch.md
> +Let's say we choose an error of 0.1%(`0.001`) with certainty of 99.8%(`0.998`) (thus probability of error 0.02% (`0.002`)). The resulting sketch will try to keep the error within 0.1% of the sum of c
```suggestion
Assume you select an error rate of 0.1% (0.001) with a certainty of 99.8% (0.998). This means you have an error probability of 0.02% (0.002). Your sketch strives to keep the error within 0.1% of the total count of all elements you've added. There's a 0.02% chance the error might exceed this—like when an element below the threshold overlaps with one above it. When you add a few items to the CMS and evaluate their frequency, remember that in such a small sample, collisions are rare, as seen with other probabilistic data structures.
```

2023-10-06 16:26 UTC, dwdougherty requested changes
Some re-wording of the text; took me a while to unwind what this paragraph was trying to convey (not your fault at all, you inherited it). Let me know if the updated wording works for you.

2023-10-24 14:36 UTC, sav-norem commented
@dwdougherty reads easier to me! just accepted that suggestion

2023-10-24 20:20 UTC, dwdougherty approved these changes
Builds correctly; approved.

2023-11-15 10:07 UTC, sav-norem commented
updated master to include all tabbed example changes - closing as superfluous

2023-11-15 10:18 UTC, sav-norem commented
merged into PR #670

2023-11-15 10:18 UTC, closed without merging